if(NOT DOWNLOAD_PATH OR NOT DOWNLOAD_URL OR NOT NODE_INCLUDE_DIR)
  message(FATAL_ERROR "DOWNLOAD_PATH, DOWNLOAD_URL, and NODE_INCLUDE_DIR are required")
endif()

set(DOWNLOAD_PATH ${DOWNLOAD_PATH})
set(DOWNLOAD_URL ${DOWNLOAD_URL})
include(${CMAKE_CURRENT_LIST_DIR}/DownloadUrl.cmake)

set(NODE_INCLUDE_DIR ${NODE_INCLUDE_DIR})
include(${CMAKE_CURRENT_LIST_DIR}/PrepareNodeHeaders.cmake)
